### ISSUE TITLE
[P5-8] Never get to /account

### ISSUE THREAD

**Issue by s1155033765** [ierg4210/shop08#1]
When browsing to /account/login, 504 Gateway Timeout (Not even /account/login/checkout)

but to /admin/login, it is correct.

Possible fix: look at /routes/auth-api.js and see app.get("/login"), add a ELSE case for this

http://i218.photobucket.com/albums/cc176/William_AOE/IERG4210/store08%20checkout%20no%20response.png

**Comment by s1155016638** [comment]
Sorry , it is because it is not implemented yet, for now it can be accessed

**Comment by zhusz** [comment]
Unrelated security hacking. Fixed now.
