### ISSUE TITLE
No authorization required for backend API

### ISSUE THREAD

**Issue by s1155030353** [ierg4210/shop08#2]
The authorization is only checked in /admin. It is suggested to check for all /admin/* pages.

Methodology:
![image](https://cloud.githubusercontent.com/assets/10591335/7498033/94f8efa2-f450-11e4-8563-da8bcf2fec51.png)
Results:
![image](https://cloud.githubusercontent.com/assets/10591335/7498058/be140156-f450-11e4-85c7-266dced0d2f7.png)

**Comment by s1155016638** [comment]
fixed by evaluating the session at all admin page

**Comment by zhusz** [comment]
Valid hacking but fixed now.
